apiVersion: v1
kind: Service
metadata:
  namespace: priyo
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: api