apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: priyo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/brilliant-dock-408207/priyo/go-react-postgres/api:1.0.2
          imagePullPolicy: IfNotPresent
          name: api
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "2"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: POSTGRES_HOST
          ports:
            - containerPort: 8000
