apiVersion: v1
kind: Service
metadata:
  namespace: priyo
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend